### ISSUE TITLE
Publicly Accessible Google API Key

### ISSUE THREAD

**Issue by utsav-devadiga** [armaan1470/Heal-ify-Health-and-Diet-Tracker-App#1]
Kindly hide the API key inside build.config file as it triggers the google authentication whenever the Api key (PAID KEYS) are exposed on the open-source platform. Since I am the owner of the key I have deactivated it.

**Comment by armaan1470** [comment]
Got it

**Comment by armaan1470** [comment]
Is the issue resolved now? I have removed the paid api key from the github
repo but I'm not sure if about the build.config so let me know if the
issue is still not resolved.
